### ISSUE TITLE
findlib-deps

### ISSUE THREAD

**Issue by udeved** [artix-linux/artools#35]
As we are organized now, for example findlibdeps works in a given repo dir.
eg find-libdeps icu would produce run in system almost nothing, but if run in world, it would spit out more libs.so.
So we got the problem, and I think its why arch have core and extra in one svn tree, that we need to join our world into system.
Any experience with submodules to eventually handle it?

jenkins runs after each successful build these checks, so best would be to join them together, since icu is in system, but its reverse depends that need rebuilds mostly in world.
There are other examples, icu is just good case.

@cromerc @DamnWidget

**Comment by cromerc** [comment]
I have a little experience with submodules now, I am using them to make every cromnix package into an individual repo. Then the parent repo syncs the submodules. Still playing with it now to learn more. The benefit to this is that a maintainer of a package can only update his packages and I don't have to give complete access to all packages to a maintainer.

**Comment by udeved** [comment]
It has many more benefits to have it like you experiment with.
Jenkins pipeline has currently its own logic to get the package pushed by parsing a changelogset object.
We could drop all that, if we can checkout a package only, like you can checkout a subtree with svn.

**Comment by cromerc** [comment]
If we want to implement it, we need a separate organization just for the packages. This is what I have:
- https://github.com/cromnix This is where all source code, tools, and misc stuff goes.
- https://github.com/cromnix-packages This is where the packages are, each package is it's own repo. Then a "master repo", which I only have locally in my notebook right now uses those repos as submodules.

This helps keep things clean so that the "cromnix" organization doesn't get flooded with thousands of git repos. All the package repos are in the "cromnix-packages" organization.

I also registered a 3rd organization called "cromnix-community". Basically it is the same idea, but open to the community to make packages, essentially "galaxy" for us.

**Comment by DamnWidget** [comment]
I already did mention the submodules solution a while ago.
If have as many repos as packages is not a major annoyance I see no problem
with it.

**Comment by udeved** [comment]
@cromerc 

Ok, why not try with a packages org @cromerc 
We can use the pipeline-playground repo to make it work with submodules.
However, I would drop the subfolders you use on cromnix.

**Comment by cromerc** [comment]
@udeved I am already in the process of dropping the subfolders on cromnix, it's just been slow since the uni has been keeping me busy.
